name: Build & Release
on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build
        run: |
          sudo gem install fpm
          mkdir arducam

          VERSION="0.1-$(date -d '+1 hour' +'%m-%d-%Y--%H-%M-%S')"
          fpm -a armhf -s dir -t deb -n arducam-camera -v "$VERSION" -C arducam -p openhd_rock5cams_VERSION_ARCH.deb
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: |
            *.deb
      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "release"
          distro: "any-distro"
          release: "any-version"
          republish: "true" # needed ONLY if version is not changing
          file: "*armhf.deb"
      - name: Push2
        id: push2
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "release"
          distro: "any-distro"
          release: "any-version"
          republish: "true" # needed ONLY if version is not changing
          file: "*arm64.deb"
      - name: Push3
        id: push3
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "release"
          distro: "any-distro"
          release: "any-version"
          republish: "true" # needed ONLY if version is not changing
          file: "*amd64.deb"